---
title: "Day12"
author: "Konstantinos Patelis"
date: "12/12/2021"
output: html_document
---

# Day 12: Passage Pathing

Solution to https://adventofcode.com/2021/day/12

```{r data}

library(tidyverse)

path <- "2021/data/data_day12.txt"

input <- read_delim(path, col_names = c("from", "to"), delim = "-")

inside <- input %>% 
  filter(!(from %in% c("start", "end")), !(to %in% c("start", "end")))

inside <- bind_rows(inside, 
                    inside %>% rename(from = to, to = from))

edges <- input %>% 
  filter((from %in% c("start", "end")) | (to %in% c("start", "end")))

proper_edges <- edges %>% 
  filter(from == "start" | to == "end")

inv_edges <- edges %>% 
  filter(!(from == "start" | to == "end")) %>% 
  rename(from = to, to = from)

edges <- bind_rows(proper_edges, 
                   inv_edges)

starts <- edges %>% 
  filter(from == "start")

ends <- edges %>% 
  filter(to == "end")

```

## Part 1

```{r}

# Part 1

paths <- bind_rows(inside, ends, tibble(from = "end", to = "end")) %>% 
  rename(node = from)

part1 <- starts
i <- 0

repeat {
  
  i <- i + 1
  inner_name <- paste0("node_", i)
  
  part1 <- part1 %>% 
    rename_with(.fn = ~ paste0("node_", i), .cols = "to")
  
  paths <- paths %>% 
    rename_with(.fn = ~ paste0("node_", i), .cols = starts_with("node"))
  
  part1 <- left_join(part1, paths) %>% 
    mutate(id = row_number())
  
  if (all(part1$to == "end")) break
  
  part1_lng <- part1 %>% 
    pivot_longer(cols = -id) %>%
    filter(name != "from") %>% 
    group_by(id, value) %>% 
    count() %>% 
    ungroup() %>% 
    mutate(check = (n > 1 & (value == tolower(value) & value != "end"))) %>% 
    group_by(id) %>% 
    summarise(check = sum(check)) %>% 
    ungroup() %>% 
    filter(check == 0) %>% 
    pull(id)
  
  part1 <- part1 %>% 
    filter(id %in% part1_lng)
  
}

nrow(part1)

```

## Part 2

```{r}

# Part 2

tictoc::tic()

paths <- bind_rows(inside, ends, tibble(from = "end", to = "end")) %>%
  rename(node = from)

part2 <- starts
i <- 0
part2_final <- NULL

repeat {
  
  i <- i + 1
  inner_name <- paste0("node_", i)
  
  part2 <- part2 %>% 
    rename_with(.fn = ~ paste0("node_", i), .cols = "to")
  
  paths <- paths %>% 
    rename_with(.fn = ~ paste0("node_", i), .cols = starts_with("node"))
  
  part2 <- left_join(part2, paths) %>% 
    mutate(id = row_number())

  part2_final <- bind_rows(part2_final,
                           part2 %>% filter(to == "end"))

  part2 <- part2 %>%
    filter(to != "end")

  if (nrow(part2) == 0) break
  
  part2_lng <- part2 %>% 
    select(-from) %>% 
    pivot_longer(cols = -id) %>%
    group_by(id, value) %>% 
    count() %>% 
    ungroup() %>% 
    filter(value != "end") %>% 
    mutate(check = (n > 2 & (value == tolower(value) & value != "end")), 
           lower = value == tolower(value)) %>% 
    group_by(id, n, check, lower) %>%
    count() %>%
    ungroup() %>%
    mutate(check = ifelse(n > 1 & nn > 1 & lower == TRUE, TRUE, check)) %>%
    group_by(id) %>% 
    summarise(check = sum(check)) %>% 
    ungroup() %>% 
    filter(check == 0) %>% 
    pull(id)
  
  part2 <- part2 %>% 
    filter(id %in% part2_lng)
  
}

nrow(part2_final)
# 116692

tictoc::toc()

```
