---
title: "Day5"
author: "Konstantinos Patelis"
date: "05/12/2021"
output: html_document
---

# Day 5: Hydrothermal Venture

Solution to https://adventofcode.com/2021/day/5

```{r}

library(tidyverse)

```


```{r data}

# tictoc::tic()

path <- "2021/data/data_day5.txt"

data <- readLines(path)

df <- tibble(string = data) %>% 
  separate(string, into = c("x1", "y1", "x2", "y2")) %>% 
  mutate(across(.fns = as.numeric))

find_edges <- function(col_1, col_2, fun) {
  
  fun(fun(col_1), fun(col_2))
  
}

xmin <- find_edges(df$x1, df$x2, min)
xmax <- find_edges(df$x1, df$x2, max)
ymin <- find_edges(df$y1, df$y2, min)
ymax <- find_edges(df$y1, df$y2, max)

grid <- matrix(data = 0, nrow = xmax, ncol = ymax)

# tictoc::toc()
# 0.01 sec elapsed

```

## Part 1

```{r part1}

# Part 1

# tictoc::tic()

solve_grid <- function(df, grid, diag = FALSE) {
  
  for (i in seq(nrow(df))) {
  
    x1 <- df %>% slice(i) %>% pull(x1)
    x2 <- df %>% slice(i) %>% pull(x2)
    y1 <- df %>% slice(i) %>% pull(y1)
    y2 <- df %>% slice(i) %>% pull(y2)

    if (x1 == x2 | y1 == y2) {
      
      grid[x1:x2, y1:y2] <- grid[x1:x2, y1:y2] + 1
      
    } else if (diag) {
      
      diag(grid[x1:x2, y1:y2]) <- diag(grid[x1:x2, y1:y2]) + 1
      
    }
    
  }
  
  grid
  
}

grid_part1 <- solve_grid(df, grid)
sum(grid_part1 >= 2)

# tictoc::toc()
# 1.97 sec elapsed

```

## Part 2

```{r part2}

# Part 2

# tictoc::tic()

grid_part2 <- solve_grid(df, grid, diag = TRUE)
sum(grid_part2 >= 2)

# tictoc::toc()
# 2.54 sec elapsed

```
